### ISSUE TITLE
Can't login with password if two-factor auth is enabled

### ISSUE THREAD

**Issue by victormours** [Scalingo/cli#1029]
👋 Hello there, I'm having an issue with version 1.30 when running `scalingo login --password-only` with an account that has two factor authentication enabled.
The same command with the same account works fine with version 1.28.

### Working behavior with scalingo-cli v 1.28

```
$ scalingo login --password-only
       Trying login with user/password:

       Username or email: victor.mours@example.fr
       Password:
       OTP: 123456

-----> Hello victor.mours, nice to see you!
```

### Bug with scalingo-cli v1.30

The cli doesn't ask for the OTP, but fails directly.

```
scalingo login --password-only
       Trying login with user/password:

       Username or email: victor.mours@example.fr
       Password:
 !     Fail to login (1/3): fail to create API token: OTP Required

       Username or email:
```

And then it loops like this for 3 tries.

**Comment by victormours** [comment]
Any news on this ? This is forcing us to disable and re-enable 2FA manually on a regular basis

**Comment by curzolapierre** [comment]
Hello @victormours, I've just picked up the issue and I'm actively working on it. Once done we'll figure out about a release of the CLI.

**Comment by curzolapierre** [comment]
The release has been done including the related fix

To download the update: https://doc.scalingo.com/platform/cli/start

Thanks for the report @victormours and sorry for the inconvenience

**Comment by victormours** [comment]
Great! Thank you so much for the fix, I appreciate it :)
