### ISSUE TITLE
Did both 1.31.0 and 1.31.2 tags get removed?

### ISSUE THREAD

**Issue by chenrui333** [Scalingo/cli#1053]
👋 looks like both 1.31.0 and 1.31.2 tags get removed? Thanks!!

relates to https://github.com/Homebrew/homebrew-core/pull/166231

**Comment by EtienneM** [comment]
Hi,

Yes indeed, we had an issue with our release process which led to the creation of a bunch of Git tags we eventually removed. The version 1.31.0 is the one we released (https://github.com/Scalingo/cli/releases/tag/1.31.0).

**Comment by chenrui333** [comment]
Thanks @EtienneM!
