### ISSUE TITLE
Linux arm build

### ISSUE THREAD

**Issue by Aethelflaed** [Scalingo/cli#145]
Is it possible to provide a linux arm build ?

I don't know how to build your app, but maybe if you autoconf ?

**Comment by Soulou** [comment]
Agreed for an ARM build, it's not a lot of extra work for us.

If you want to build the app you have to install the go compiler http://golang.org/

Then you can use go environment variable to choose your target, for instance:

```
GOOS=linux GOARCH=arm GOARM=9 go install github.com/Scalingo/cli
```

**Comment by Soulou** [comment]
We'll publish 1.1.1 today, it will include a linux arm build
