### ISSUE TITLE
destroy command is too tolerant

### ISSUE THREAD

**Issue by Zyko0** [Scalingo/cli#155]
destroy command's confirmation asks the user to enter the name of its application again.
But there is too much tolerance in the confirmation i.e:
If I want to destroy `myapp` and that you type "myapp jiezoijezdizejd" (notice the space)
```bash
scalingo -a myapp destroy
/!\ You're going to delete myapp, this operation is irreversible.
To confirm type the name of the application: myapp jiezoijezdizejd
-----> App myapp has been deleted
```

It must come from a Scan() taking the space character as a split character or whatever..

**Comment by Soulou** [comment]
:+1:
