### ISSUE TITLE
[issue] Unable to login using git bash on Windows 10

### ISSUE THREAD

**Issue by Aethelflaed** [Scalingo/cli#160]
Hi,

I'm unable to login using git bash on windows 10.

Step to reproduce:
1. Boot Windows 10 with scalingo installed, e.g. in ~/bin
2. Open git bash with .bashrc adding ~/bin to the path
3. $ scalingo.exe apps

Output:
> You need to be authenticated to use Scalingo client.
> No account ? → https://scalingo.com
> Username or email: EMAIL@EXAMPLE.COM
> Password: Fail to login (1/3): Fail to read character with win#ReadConsoleInput (Incorrect function.)
> Username or email:

Using cmd.exe, it works as expected (except for the password, which shows some ***, but maybe this is expected on windows).

Once the initial login has been done using cmd.exe, the app doesn't ask for login again and works also on git bash.

**Comment by Zyko0** [comment]
I'm on it..

For the moment I can't suggest you anything except running `bash` from `cmd.exe`:

```bash
> cd C:/Program Files/Git/bin
> bash
```

This is not an ideal solution, but it would let you use `bash` on Windows until we find a fix.
This is a bug related to Windows 10 AND the `git-bash`.

Sorry for the inconvenience

**Comment by jaredbidlow** [comment]
I have this issue.
And, with using the alternative, cmd.exe, I cannot enter the password because it inserts a character when I press enter.
