### ISSUE TITLE
[Suggestion][Environment] Massive set of variables thanks to a .env file

### ISSUE THREAD

**Issue by Soulou** [Scalingo/cli#176]
Example:

```
scalingo -a env-import ./.env.production
```

**Comment by Zyko0** [comment]
Good idea! And what about this `env-import` also reading on standart input?
Which means you can edit the current environment like "mass edit" function from the dashboard.
It would be more logical for users coming from dashboard to cli, or vice versa.

e.g:

```
$ scalingo -a env-import --interactive
-------> Edit your variables environments and press Ctrl + C when you want to save.
MYVAR=myvalue
MYVAR2=myvalue2
```

One thing would be to see how hard it is to navigate through your environment this way.

**Comment by Soulou** [comment]
By opening the default editor of the user

```
scalingo -a env-import --interactive
..
# Open vim/emacs/nano with all variables
# The person edit it and save
# Environment is updated
```

**Comment by Zyko0** [comment]
:+1:
