### ISSUE TITLE
Empower users to let them build the CLI

### ISSUE THREAD

**Issue by pimpin** [Scalingo/cli#204]
Could you please give a recipe/script to build the client ?
And maybe add a line of related doc in in the Readme.

I'm currently looking forward [ssh login feature merged in master](https://github.com/Scalingo/cli/commit/ce3f19405fdb83439cc076d421fbc44f3287e519) but not yet released.

Thanks a lot.

PS : It might be existing or obvious, but I didn't know Go and cannot see it

**Comment by pimpin** [comment]
I found [this comment](https://github.com/Scalingo/cli/issues/145#issuecomment-142208297) and will make some tries.

**Comment by pimpin** [comment]
Ok I've found [the script](https://github.com/Scalingo/cli/blob/master/dists/make-release.sh) but got an issue running it :

```
$ ./dists/make-release.sh -v 1.3.0-alpha
tag: 1.3.0-alpha
Current branch master is up to date.
goxc not found, install...
./dists/make-release.sh: line 65: goxc: command not found
Already on 'master'
Your branch is up-to-date with 'origin/master'.
```

I need goxc which [depends on go build from source](https://github.com/laher/goxc#installation)... I give up for now.

**Comment by Soulou** [comment]
Hi @pimpin,

You're completely right, I'm going to explain how to build the project more clearly in the readmy.

For now, you don't need to use the release script, is specific for us when we want to build a releases for the different platform and such.

To install the CLI, you need the following: Go runtime (https://golang.org/doc/install)

Then all you have to do is to run:

```
go get github.com/Scalingo/cli/scalingo
```

And that's it the `scalingo` binary will be present in your $GOPATH/bin/scalingo

```
$GOPATH/bin/scalingo -v
Scalingo Client version 1.3.0-dev
```

**Comment by pimpin** [comment]
Thanks @Soulou 
It's wonderful it works. Let's try now to use ssh login feature.
