### ISSUE TITLE
Add commands 'deployments' and 'deployments-log'

### ISSUE THREAD

**Issue by Soulou** [Scalingo/cli#217]
* List all the deployments and their state
`scalingo deployments`

* Display log of deployments for a given deployment (`-f' flag to stream current deployment logs)
`scalingo deployments-log [-f] <id>`

API client should be updated here first: https://github.com/Scalingo/go-scalingo

API doc here: http://developers.scalingo.com/

**Comment by johnsudaar** [comment]
Done #222
