### ISSUE TITLE
[Autocomplete] Endpoint is set to https://api.scalingo.com even when we run the CLI with SCALINGO_API_URL

### ISSUE THREAD

**Issue by utay** [Scalingo/cli#232]
This issue applies only to the notification remove command.
Example:
`SCALINGO_API_URL=http://localhost:3001 ./scalingo -a testtest notifications-remove` won't autocomplete 

See [cmd/notifications.go](https://github.com/Scalingo/cli/blob/master/cmd/notifications.go) and [cmd/autocomplete/notifications_remove.go](https://github.com/Scalingo/cli/blob/master/cmd/autocomplete/notifications_remove.go)

**Comment by johnsudaar** [comment]
Local environment variable are not passed to the autocomplete script (tested on bash version 4.3.30 and zsh 5.0.7).

Using
`export SCALINGO_API_URL=http://localhost:3001` works just fine.
