### ISSUE TITLE
CLI is freezing with some versions of MacOS/iTerm

### ISSUE THREAD

**Issue by yannski** [Scalingo/cli#250]
Specifically with MacOS Sierra + iterm2 version Build 3.0.20160913-nightly + Scalingo Client version 1.3.1

**Comment by brunto** [comment]
Hi, any news about this issue?

**Comment by yannski** [comment]
Not yet. We're busy on other fronts.

**Comment by brunto** [comment]
When I quickly hit Enter at the step "-----> Process 'xxxxx' is starting..." then everything works.

**Comment by Soulou** [comment]
1.4.0 has been http://cli.scalingo.com/, could you try the version and tell us if you still encounter this issue?

**Comment by brunto** [comment]
It works, you can close this issue.
