### ISSUE TITLE
Scalingo update does not work

### ISSUE THREAD

**Issue by EtienneM** [Scalingo/cli#272]

**Comment by Soulou** [comment]
Details?

Expected behavior?

Current behavior?

**Comment by EtienneM** [comment]
Scalingo help mentions the command `update` to `Update 'scalingo' client`. Executing this command does not actually update the CLI. It just prints:
```-----> Your Scalingo client (1.1.0) is out-of-date: some features may not work correctly.
       Please update to '1.4.0' by reinstalling it: http://cli.scalingo.com
```
