### ISSUE TITLE
Is it possible to get the time before lock release?

### ISSUE THREAD

**Issue by yannski** [Scalingo/cli#333]
When getting the error "Deployment error: repository xxxx is locked (reason: a deployment is running)", is it possible to get the time before lock release?

**Comment by Soulou** [comment]
It's not related to the CLI, and it's not, currently it's as soon a the next output line of the deployment failed to be sent. This problem will be fixed by allowing multiple git deployment in parallel like it is done with github deployments.

**Comment by yannski** [comment]
Invalid since parallel building in production
