### ISSUE TITLE
Add routing settings to the CLI

### ISSUE THREAD

**Issue by johnsudaar** [Scalingo/cli#344]
- [ ] Force HTTPS
- [ ] Sticky session
- [ ] Canonical

**Comment by EtienneM** [comment]
I don't really know what would be the best command name for these commands..  Actually canonical domain is a bit different than the others. Suggestions:

- `scalingo -a my-app routing-settings [force-https | sticky-session]-enable`
- `scalingo domains-canonical-[un]set` to stick with the other Custom Domains commands
- `scalingo canonical-domaisn-[un]set`

**Comment by johnsudaar** [comment]
I think that something like:
`scalingo -a my-app [force-https |  sticky-session] [enable|disable]`

Would be pretty nice/
