### ISSUE TITLE
Allow to disable version update check

### ISSUE THREAD

**Issue by Horgix** [Scalingo/cli#361]
From why I understand from the update warning by the CLI, the `strace` I ran on it, and the [check.go sources](https://github.com/Scalingo/cli/blob/41809bde2c9aeb2f4008e49181622d80dd0652fa/update/check.go), it looks like **the CLI send a request to [cli-dl.scalingo.io/version](https://cli-dl.scalingo.io/version) everytime to know if it's up-to-date**.

It also looks like it's currently **not possible to disable this check**, and I know that some people don't really like CLI that "call home" (I'm among them, especially when running a `--help` or `--version`) :wink: 

It would be cool to **be able to disable it**, for example with an environment variable (that's [what Hashicorp are doing on Packer](https://www.packer.io/docs/other/environment-variables.html#checkpoint_disable)). The best would be to have it opt-in but I think you'll prefer to keep it ON by default don't you?

If you're OK with this, I would like to send the PR implementing it :slightly_smiling_face:

**Comment by Soulou** [comment]
Hi there, we're completely ok with this. To be fully transparent we're not doing anything from this call to cli-dl (no stat for instance), its purpose is only to notify when a new version is released, waiting for an auto-upgrade mecanism to be developed. (Which will be disablable ;-))

**Comment by Horgix** [comment]
I definitely trust you on that and even if you were doing stats on it it wouldn't be __that__ much of a problem anyway. Just thought I would open this since I was surprised to see a `--help` doing HTTP requests :smile: 

I just saw #174 and #175 about the auto-upgrade. Definitely not a fan of this and would definitely appreciate if it was possible to disable this kind of thing!

**Comment by yannski** [comment]
@horgix you're right, the help command should not do any HTTP requests, there should be a dedicated subcommand for version checking and the auto-upgrade should be disconnectable
