### ISSUE TITLE
Add a db-backup-download command

### ISSUE THREAD

**Issue by johnsudaar** [Scalingo/cli#370]

**Comment by jgigault** [comment]
Hello Scalingo, 
Do you have an update for this feature?
Thank you

**Comment by yannski** [comment]
@jgigault work is in progress. The Database API is being documented here: https://developers.scalingo.com/databases It may be sufficient to automate what you want. Updating the CLI will be done in the coming weeks to add database support (backups listing/download).

**Comment by jgigault** [comment]
@yannski awesome! thanks

**Comment by EtienneM** [comment]
Fixed by #397
