### ISSUE TITLE
PS command should also show one-off containers

### ISSUE THREAD

**Issue by johnsudaar** [Scalingo/cli#381]
The `scalingo ps` command only show container that are described in the user's  `Procfile`. It would be nice to also show one-off containers (attached and detached).

**Comment by Soulou** [comment]
I agree, I think that a nice upgrade would be to have

scalingo ps : containers actually running
scalingo scale : without argument, see current formation configuration
scalingo stop : stop a container (especially useful for detached one-off)

Any thought about this?

**Comment by EtienneM** [comment]
What if I type `scalingo stop web-2`? Does it scale down my app?

**Comment by Soulou** [comment]
I would say, no. It's just stop the container, as specified.

A restart, or a deployment would restart it (restore the formation).

A stopped container would not be billed already (it's how it work today, nothing to change)

**Comment by EtienneM** [comment]
OK I didn't we had such things as stopped container.

**Comment by EtienneM** [comment]
@johnsudaar What you are talking about is already described in #315 ;)
