### ISSUE TITLE
[db-console commands] it should be possible to enforce the environment variable used

### ISSUE THREAD

**Issue by Soulou** [Scalingo/cli#387]
```
scalingo -a app redis-console --env REDIS_SIDEKIQ_URL
scalingo -a app redis-console --env REDIS_URL
```

**Comment by abgit** [comment]
+1 on tunnel

```
scalingo -a app db-tunnel CUSTOM_PGSQL_DSN

scalingo -a app pgsql-console CUSTOM_PGSQL_DSN
```

This feature has a particular relevance when we want to login with another user (instead of default db root).

**Comment by abgit** [comment]
If we don't want to use default (root) db credentials and if we deleted SCALINGO_POSTGRESQL_URL env, it's not possible to have a pgconsole with another user.
Without SCALINGO_POSTGRESQL_URL env, scalingo cli is unable to detect postgresql addon and says addon doesn't exist (and that's not true too).

```
scalingo --app app addons
+------------+-----------------------------------------+--------------------+
|   ADDON    |                   ID                    |        PLAN        |
+------------+-----------------------------------------+--------------------+
| PostgreSQL | ad-6a36d978-.....                       | ....               |
| .....
+------------+-----------------------------------------+--------------------+
```
When trying to use pgsql console (without SCALINGO_POSTGRESQL_URL defined) scalingo maybe should say that SCALINGO_POSTGRESQL_URL don't exist (and a custom env should be passed on cli) 
```
scalingo --app app pgsql-console
 !     An error occured:
       no scalingo_postgresql addon detected
```
maybe with an even better error string:
```
scalingo --app app pgsql-console
 !     An error occured:
       no scalingo_postgresql addon detected or SCALINGO_POSTGRESQL_URL undefined
```

and this would be a better cli alternative, passing a custom env:
```
scalingo --app app pgsql-console MYCUSTOM_POSTGRESQL_URL
```
