### ISSUE TITLE
[one-off] There should be a way to stop a one-off container

### ISSUE THREAD

**Issue by Soulou** [Scalingo/cli#404]

**Comment by EtienneM** [comment]
Isn't it a duplicate of #315 ?

**Comment by Soulou** [comment]
Hmmm I don't know, it's related but not duplicate, just have a look at the example of #315, I'm renaming this issue `to stop a one-off container`

**Comment by yanjost** [comment]
a one-off container should be killed when the connection with the client is broken, don't you think ?

**Comment by johnsudaar** [comment]
@yanjost Yes this is the case. But you can also run detached one-off, in this case there is no connection between the container and the client.

UP !

**Comment by yanjost** [comment]
How does the customer know a one-off container is running then ?

**Comment by johnsudaar** [comment]
`scalingo -a MYAPP stats`

**Comment by Soulou** [comment]
Which is crappy, they should be visible with `ps`

**Comment by yanjost** [comment]
They should even be visible in the application dashboard
