### ISSUE TITLE
[one-off] There should be a way to download the audit logs

### ISSUE THREAD

**Issue by johnsudaar** [Scalingo/cli#412]

**Comment by yannski** [comment]
Maybe not? Let it go through the API?

Le lun. 29 avr. 2019 à 15:50, Jonathan Hurter <notifications@github.com> a
écrit :

**Comment by johnsudaar** [comment]
Why ? Anything should be possible via our CLI.

**Comment by yannski** [comment]
It's debatable :)

Le lun. 29 avr. 2019 à 16:43, Jonathan Hurter <notifications@github.com> a
écrit :

**Comment by EtienneM** [comment]
A new issue about that has been opened in https://github.com/Scalingo/cli/issues/1253
