### ISSUE TITLE
[stats] Add container creation date

### ISSUE THREAD

**Issue by EtienneM** [Scalingo/cli#416]
https://app.intercom.io/a/apps/w4oogu7s/inbox/inbox/conversation/22203678135

**Comment by Soulou** [comment]
I think it should be part of the new version of the `scalingo ps` commant, which should not just list the `ContainerTypes` but list the running containers one-off included? with their type/size/creation_date etc.

**Comment by EtienneM** [comment]
Oh yes, this issue is definitely related to #381
