### ISSUE TITLE
scalingo login should really call the API 

### ISSUE THREAD

**Issue by yannski** [Scalingo/cli#417]
and the login printed in the output of the command should be the result of what the API answered

**Comment by yannski** [comment]
whoami and self should certainly do the same

**Comment by Soulou** [comment]
What was the problem first identified?

**Comment by yannski** [comment]
When debugging what a user is doing with the CLI, it's not really possible to know if the person is authenticated or not and with which account.

**Comment by yannski** [comment]
BTW, on the rhetorical side, "whoami" and "self" by just looking a file on a local machine does not seem right to me. This information can just come from Scalingo's side.
