### ISSUE TITLE
[backup-download] Failed to keep retro-compat

### ISSUE THREAD

**Issue by EtienneM** [Scalingo/cli#459]
@johnsudaar 	@EtienneM 	FYI this broke one of our scripts that was using the `backup-download` command. I looks like here (https://github.com/Scalingo/cli/pull/452/files#diff-6eae5f17654b235c68ab2bb17d69c9f2L32) you tried to keep the old `backup-download` command functional but with a warning; but it looks like the legacy command descriptor is missing the `Flags` parameter causing it to reject every invocation that has any flag, and not show the warning:

```
$ scalingo -a my-app backup-download --addon st-12345-67890 --backup abcdef12345
Incorrect Usage: flag provided but not defined: -addon

NAME:
   scalingo backup-download - Download a backup

USAGE:
   scalingo backup-download [command options] [arguments...]

CATEGORY:
   Addons

DESCRIPTION:
     Download a specific backup:
    $ scalingo --app my-app --addon addon_uuid backups-download --backup my_backup

    # See also 'backups' and 'addons'

OPTIONS:
   --region value  Name of the region to use

Fail to run command: flag provided but not defined: -addon
```

_Originally posted by @jonathanperret in https://github.com/Scalingo/cli/pull/452#issuecomment-515901078_

**Comment by jonathanperret** [comment]
Thanks for the quick fix ❤️
