### ISSUE TITLE
Add support for SOCKS proxy

### ISSUE THREAD

**Issue by EtienneM** [Scalingo/cli#468]
It should not be that hard: https://stackoverflow.com/a/33586260/1351436

**Comment by yannski** [comment]
Maybe it's even already functionnal!

Le ven. 23 août 2019 à 09:11, Étienne M. <notifications@github.com> a
écrit :

**Comment by EtienneM** [comment]
https://app.intercom.io/a/apps/w4oogu7s/inbox/conversation/23360520111

**Comment by EtienneM** [comment]
I just successfully used the HTTP_PROXY variable with a local SOCKS5 proxy. I asked our customer to also test this in order to confirm it works.

**Comment by EtienneM** [comment]
Other possible libs: 
https://news.ycombinator.com/item?id=22681960
https://github.com/txthinking/socks5
