### ISSUE TITLE
Add --username option to scalingo login

### ISSUE THREAD

**Issue by johnsudaar** [Scalingo/cli#469]
It would help users with multiple accounts.

**Comment by Soulou** [comment]
Can you explain the scenario a bit more?

**Comment by johnsudaar** [comment]
If a user has multiple accounts and if one has a SSH key scalingo login will automatically login the account with the SSH key.

The only way to login another user is to generate a token on the dashboard and use with: `scalingo login --api-token`

Having a `scalingo login --username johnsudaar` would be smarter and check if the key works and if not will ask for a password.

**Comment by unuseless** [comment]
Progress on this issue or on #276 would really help a lot.  I need to manage multiple accounts on the command line, and need to switch between accounts for commands, and also for git push.  (For git, we deploy to our staging account first.  If that works, we deploy from the same repository to the production account.)
It should be possible to switch accounts.

@Soulou If you know any workaround, please let us know.

**Comment by Soulou** [comment]
I feel that adding `--username` is a bit of duck taping and is not really elegant. I would rather see #276 implemented.

**Comment by Soulou** [comment]
@johnsudaar do you agree with me on this?

**Comment by unuseless** [comment]
@Soulou Yes, go for #276 , that would be good!
