### ISSUE TITLE
Encrypted key with new OpenSSH header for private keys seems to be broken

### ISSUE THREAD

**Issue by Soulou** [Scalingo/cli#470]
```
-----BEGIN OPENSSH PRIVATE KEY-----
```

User wasn't able to type their passphrase, it was directly displaying an error:

```
Fail to connect to SSH server: Invalid SSH key or password: ssh: cannot decode encrypted private keys
```

**Comment by EtienneM** [comment]
https://app.intercom.io/a/apps/w4oogu7s/inbox/inbox/search/conversations/23446486723

**Comment by EtienneM** [comment]
Same issue with `scalingo login --ssh --ssh-identity ./test`

**Comment by EtienneM** [comment]
This is kind of related to #399. Except that now the issue only arise when the key is encrypted with a passphrase. Actually the dependency we use to read private key files is `golang.org/x/crypto/ssh`. And it seems it is not yet able to read such files: https://github.com/golang/crypto/blob/master/ssh/keys.go#L878-L880

**Comment by EtienneM** [comment]
Oh no... It's just that our code calls `ssh.ParsePrivateKey` instead of `ParsePrivateKeyWithPassphrase` if needed

**Comment by EtienneM** [comment]
The issue is that we fail to detect the key is encrypted. We check this like that: `strings.Contains(p.Block.Headers["Proc-Type"], "ENCRYPTED")`. The `golang.org/x/crypto/ssh` does the same thing so it's probably how we should handle that. But the header in my case is empty:

```
TYPE: "OPENSSH PRIVATE KEY"
HEADERS: map[string]string{}
```

**Comment by Soulou** [comment]
Actually it's because this Proc-Type header is only present in the old format.

With the new format, there is no PEM header to re at all.

**Comment by EtienneM** [comment]
up : https://app.intercom.io/a/apps/w4oogu7s/inbox/inbox/all/conversations/24870997728
