### ISSUE TITLE
`db-tunnel` auto-reconnection fails when connection is lost

### ISSUE THREAD

**Issue by jonathanperret** [Scalingo/cli#488]
When the connection to the DB server is broken (e.g. when the DB server crashes or it decides to evict the client), the `db-tunnel` command goes into a loop of `Fail to reconnect, waiting 10 seconds...` instead of successfully reconnecting.

Example:
```
$ scalingo -a my-app db-tunnel SCALINGO_REDIS_URL &
Building tunnel to ….redis.dbs.scalingo.com:12345
You can access your database on:
127.0.0.1:10000

$ redis-cli -u $(scalingo -a my-app env|awk -F= '/^SCALINGO_REDIS_URL/{sub(/@.*/,"@localhost:10000",$2); print $2}')
Connect to ….redis.dbs.scalingo.com:… [1]

localhost:10000> SHUTDOWN
End of connection [1]
Connection broken, reconnecting...
not connected> exit
Fail to reconnect, waiting 10 seconds...
Fail to reconnect, waiting 10 seconds...
Fail to reconnect, waiting 10 seconds...
…
```

Restarting the client (e.g. `redis-cli`) is not enough: the tunnel does not respond.

Restarting the `db-tunnel` command allows it to work again.

The behaviour I expected was for the tunnel to be reestablished.

**Comment by EtienneM** [comment]
Waiting for this issue to be solved, you can create the DB tunnel with OpenSSH client: https://doc.scalingo.com/platform/databases/access#build-the-tunnel-with-the-openssh-client
