### ISSUE TITLE
[Feature request] Provide a `local`command to run the application locally

### ISSUE THREAD

**Issue by yanjost** [Scalingo/cli#500]
Feature request: provide a `scalingo local` command which will start the processes declared in the Procfile

**Comment by Soulou** [comment]
That's a nice idea, but it supposes that everything is installed locally to run the different processes. A lot of people are using tools like docker-compose etc. to run the project locally and ensure an identical environment between colleagues.

There are existing tools like `foreman` http://ddollar.github.io/foreman/, would you fit your needs?

**Comment by yanjost** [comment]
Well, at the moment I'm using `honcho`, a python alternative to `foreman`, I'm not ready to install ruby just to run my app.

I didn't want to get the ** exact ** same environement, but it would be practical to launch the same processes

Please see below the script I'm using to test my Procfile before launching

```bash

#!/usr/bin/env bash

rm -f /tmp/Procfile
cat run_as_scalingo_addons.txt >>/tmp/Procfile
echo >>/tmp/Procfile
cat Procfile | grep -v postdeploy >>/tmp/Procfile

pipenv run honcho start -f /tmp/Procfile $*

```
