### ISSUE TITLE
Logs should be sorted by the client by chunk of 100 lines/200-300ms for instance

### ISSUE THREAD

**Issue by Soulou** [Scalingo/cli#511]
Scalingo logs system does not guarantee the order of incoming log lines.

Thus when an app is generating a lot of logs, `scalingo logs -f` will display them in the wrong order.

Most people don't care having their real time logs with a bit of delay. Thus, I propose to create a sorting logs on the client side.

Using a buffer of N thousands line or a duration (according to which step happens first). When the tick happen, the pack of logs is sorted and displayed to the user.

**Comment by EtienneM** [comment]
Up: https://app.intercom.com/a/apps/w4oogu7s/inbox/inbox/all/conversations/36000003530
