### ISSUE TITLE
[storky] Should display an error message if data step failed

### ISSUE THREAD

**Issue by EtienneM** [Scalingo/cli#529]
[DEBUG]2020/03/13 18:42:23 APIRequest Error: [400] POST https://api.agora-fr1.scalingo.com/v1/apps/biniou/region_migrations/d411d6f1-9b54-43a8-8a4b-e1d97a29288c/run
[DEBUG]2020/03/13 18:42:23 {"error":"cannot run step data while in status error"}

**Comment by Soulou** [comment]
Related to https://github.com/Scalingo/cli/pull/528, I'm closing, it will be fixed at hte next release
