### ISSUE TITLE
access denied

### ISSUE THREAD

**Issue by KHADIM-hub** [Scalingo/cli#610]
j'ai mon page d'acceuil qui saffiche mais il demande d'autorisation dacces pour rediriger dans d'autre page

**Comment by EtienneM** [comment]
Bonjour,

Je ne suis pas certains de bien comprendre le souci que vous rencontrez. Nous avons un tchat de support disponible en bas à droite sur le dashboard web de Scalingo (https://my.osc-fr1.scalingo.com/apps). Je vous invite à contacter le support par ce biais pour ce genre de problème. 

Si vous êtes sûr que le souci provient de notre outil en ligne de commande, je vous invite à rouvrir cette issue en fournissant plus de détails : capture d'écran des problèmes que vous voyez, description des commandes que vous avez tapées et les messages qui s'affichent, etc.

**Comment by KHADIM-hub** [comment]
Bonjour si je client sur les liens il maffiche un page blanche avec access denied

**Comment by KHADIM-hub** [comment]
![Uploading Capture.PNG…]()

**Comment by KHADIM-hub** [comment]
![Capture1](https://user-images.githubusercontent.com/76659962/103998708-2607ff00-5194-11eb-8db0-bed57607ac37.PNG)

**Comment by EtienneM** [comment]
Sur quel lien cliquez-vous ? Quelle commande avez-vous tapée pour obtenir ce lien ? 

Vous avez ouvert une issue indiquant que notre outil en ligne de commande ne fonctionne pas. Cependant je ne vois rien dans votre descriptif d'issue qui concerne Scalingo ou notre outil en ligne de commande. Merci de fournir plus d'information pour que nous puissions comprendre ce que vous avez réalisé comme actions pour arriver à cet état. Si votre problème ne concerne pas notre outil en ligne de commande, merci de passer par le support inclut sur notre dashboard web plutôt que par ici.

**Comment by KHADIM-hub** [comment]
Le site fonction sur mon serveur local WampServer mais lorsque je l’ai heberger dans votre serveur il me signal refue daccess dans mes autre page  Provenance : Courrier pour Windows 10 De : Étienne M.Envoyé le :vendredi 8 janvier 2021 09:37À : Scalingo/cliCc : KHADIM-hub; AuthorObjet :Re: [Scalingo/cli] access denied (#610) Sur quel lien cliquez-vous ? Quelle commande avez-vous tapée pour obtenir ce lien ?Vous avez ouvert une issue indiquant que notre outil en ligne de commande ne fonctionne pas. Cependant je ne vois rien dans votre descriptif d'issue qui concerne Scalingo ou notre outil en ligne de commande. Merci de fournir plus d'information pour que nous puissions comprendre ce que vous avez réalisé comme actions pour arriver à cet état. Si votre problème ne concerne pas notre outil en ligne de commande, merci de passer par le support inclut sur notre dashboard web plutôt que par ici.—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or unsubscribe.

**Comment by EtienneM** [comment]
je vous confirme que ceci n'est pas un souci avec notre outil en ligne de commande. Merci de contacter notre support par mail à support@scalingo.com ou via le tchat embarqué sur votre dashboard web.
