### ISSUE TITLE
[Backups] "Selected the most recent backup" is print to stdout when using "--output -"

### ISSUE THREAD

**Issue by Kocal** [Scalingo/cli#645]
Hi! 

I'm using Scalingo 1.20.0, and I have an issue while trying to download the most recent backup and output it to stdout, this way I can easily uncompress it with `tar` and import SQL statements to `pg_restore`.

You can reproduce by running:
```shell
scalingo -a <project_name> --region osc-fr1 --addon <addon_id> backups-download --output - > database
head database
```
You can see `Selected the most recent backup` at the first line:
![image](https://user-images.githubusercontent.com/2103975/114449015-929bfb00-9bd4-11eb-9bfa-0f6a24aa23f6.png)

I'm not familiar with the source code or with Go, but it looks like [this message is written](https://github.com/Scalingo/cli/blob/master/db/backup_download.go#L35) before writers have been configured.

As a current workaround, I won't use `--output -` but the _classical_ way (`--output my_file.tar.gz`, `tar xzvf my_file.tar.gz`) .

Thanks! :)

**Comment by Soulou** [comment]
It seems a really legit inquiry, it will be done :-)

**Comment by Kocal** [comment]
Thanks!
