### ISSUE TITLE
[Logs] Flag to reorder/sort logs

### ISSUE THREAD

**Issue by cyrille-sg** [Scalingo/cli#656]
Scalingo logs can be unsorted given the infrastructure nature. For ex a error stack with lines 1 to 4 can be displayed in the CLI (or the app) under the form line 1-3-2-4. It is perpetuating the reading.
One way to reorder is to use ```scalingo --app <app> logs --lines 1000 | sort -k1``` but it will remove coloration.
It will be nice to have a flag to reorder logs.

**Comment by EtienneM** [comment]
This is not really possible to easily do it. The logs come in as a stream. If we add a flag to sort the logs, it means we first need to sort ALL logs lines in RAM. It is not something we want to do. Hence we won't implement this flag.
