### ISSUE TITLE
`scalingo run`: can't use `=` in environment variable values

### ISSUE THREAD

**Issue by jonathanperret** [Scalingo/cli#673]
I tried to pass an URL containing a `=` character into an environment variable for a `scalingo run` command and here's the error I encountered:

```
scalingo run -a pix-api-integration -e TEST=1=2 'echo $TEST'
 !     An error occurred:
       Invalid environment, format is '--env VARIABLE=value'
```

I think it should be possible to pass environment variables containing `=` in their value. It looks like the argument parser is a bit too restrictive here.

**Comment by EtienneM** [comment]
Thanks for reporting, I agree environment variable containing `=` should be accepted
