### ISSUE TITLE
[Addons/Logs] Add an alias for addons logs

### ISSUE THREAD

**Issue by brandon-welsch** [Scalingo/cli#683]
Like `logs` command but for database addons.

**Comment by brandon-welsch** [comment]
Oh, it's already available. But it's not very clear how to access it.

Example of the current implementation:
```shell
scalingo -a ADDON_NAME --addon ADDON_UUID logs
```

Perhaps adding an alias to this command would make sense. For example:
```shell
scalingo -a ADDON_NAME addons-logs ADDON_UUID
```

**Comment by yannski** [comment]
From a user PoV I would prefer to be able to type:

```
scalingo -d DATABASE_UUID logs
```

**Comment by btrd** [comment]
> Yes indeed, we could also add the flag --database | -d to the logs command as an alias of the --addon flag.

So if other types of addon also have logs, the `--database` flag would also work? I think this should be considered when we implement databases as first citizens, to be sure we won't need to add breaking modifications in the CLI.

```
scalingo -a APP_NAME --addon ADDON_UUID logs
```

What's the initial problem with this notation? Do we have cases of customers who had difficulties with it?
