### ISSUE TITLE
After running a detached one-off, the --region is missing

### ISSUE THREAD

**Issue by btrd** [Scalingo/cli#706]
Example:
```
# sc run rails runner "CarrierWave.clean_cached_files\!" -a my-app --region osc-secnum-fr1 --detached
Starting one-off 'rails runner CarrierWave.clean_cached_files!' for app 'my-app'.
Run `scalingo -a my-app logs -F one-off-2432` to get the output
```

On this command the `--region` is missing `scalingo -a my-app logs -F one-off-2432`

**Comment by EtienneM** [comment]
Mmmmh I don't know. The `--region` parameter is not mandatory. There are many cases (actually most cases) where the `--region` parameter is not needed. Most customers will never need this flag as they only have access to the osc-fr1 region. Hence I'm not sure we want to change the output of the command here 🤔

**Comment by EtienneM** [comment]
@btrd Did you open this issue because of some users complaints? Or by yourself after using the CLI?

**Comment by EtienneM** [comment]
We agreed with Soulou to keep this issue

**Comment by EtienneM** [comment]
I would also like the displayed command to use long options (e.g. `--app` instead of `-a`)

**Comment by btrd** [comment]
@EtienneM By myself (as a user who complaint :p)

I think the CLI should return a working command (so in this case with the region as it's needed).

It's not a big issue, so feel free to close it (if you have good reason)
