### ISSUE TITLE
Autoscaler min-container example to 1 but must be at least 2

### ISSUE THREAD

**Issue by flibustenet** [Scalingo/cli#716]
`
DESCRIPTION:
   Add an autoscaler to an application. It will automatically scale the application up or down depending on the target defined for the given metric.

   All options are mandatory.

   Example
     scalingo --app my-app autoscalers-add --container-type web --metric cpu --target 0.75 --min-containers 1 --max-containers 3

$ scalingo -a xxx autoscalers-add --container-type web --metric cpu --target 0.75 --min-containers 1 --max-containers 3
 !     An error occurred:
       * min_containers → must be at least set to 2
`

Minimum 2 is documented. But still hope you find a solution to come back to 1 !

**Comment by EtienneM** [comment]
Thanks for the report, we will fix the example
