### ISSUE TITLE
[windows] 1.23.0 version of the CLI doesn't work properly

### ISSUE THREAD

**Issue by brandon-welsch** [Scalingo/cli#735]
```
Les commandes, par exemple “scalingo apps” ne retournent rien, tournent dans le vide sans rien afficher.
```

Impact a customer: https://app.intercom.com/a/inbox/w4oogu7s/inbox/shared/all/conversation/12375700072124

**Comment by brandon-welsch** [comment]
On Windows with a Git Bash shell:
```
Brandon@Scalingo MINGW64 ~
$ scalingo apps
interrupt catched, aborting…

Brandon@Scalingo MINGW64 ~
$ DEBUG=1 scalingo apps
[DEBUG]2022/06/23 18:22:21 [Regions] Use the cache
```

Works with the `--region` flag.

**Comment by johnsudaar** [comment]
Related to [SRE-573]

**Comment by EtienneM** [comment]
It seems that it's the region detection which fails. The following does *not* work (hangs foreever):

```
DEUBG=1 scalingo --app my-app apps-info
```

But this work:

```
DEUBG=1 scalingo --region osc-fr1 --app my-app apps-info
```

**Comment by brandon-welsch** [comment]
Another customer has the issue: https://app.intercom.com/a/apps/w4oogu7s/inbox/inbox/3379738/conversations/12375700081105
