### ISSUE TITLE
Investigate GoReleaser for the CLI releases

### ISSUE THREAD

**Issue by EtienneM** [Scalingo/cli#749]
https://goreleaser.com/

**Comment by curzolapierre** [comment]
Goreleaser has a github action that is really easy to use https://github.com/marketplace/actions/goreleaser-action

**Comment by curzolapierre** [comment]
Goreleaser has a macOS Universal Binaries option that can help for: https://github.com/Scalingo/cli/issues/609
Cf: https://goreleaser.com/customization/universalbinaries/
