### ISSUE TITLE
Alert if you're allowed to reach an app because you're admin

### ISSUE THREAD

**Issue by btrd** [Scalingo/cli#771]
Add a warning if we access an app where we are only admin. The same way we do on the dashboard.
<img width="804" alt="Capture d’écran 2022-08-22 à 15 29 17" src="https://user-images.githubusercontent.com/1385737/185934261-b6746e2e-21d1-4b6a-b121-2662dabf6f0c.png">

**Comment by yohann-bacha** [comment]
Hasn't this been implemented in [this pull request](https://github.com/Scalingo/cli/pull/932)?

**Comment by Soulou** [comment]
Agreed
