### ISSUE TITLE
[Regression] The CLI documentation should be checked because of the urfave/cli v2 migration

### ISSUE THREAD

**Issue by QuentinEscudierScalingo** [Scalingo/cli#788]
The migration introduced by the urfave/cli v2 migration by the pr #774 changed the way commands are done.
Some example in the CLI help are now deprecated c.f.: #787

**Comment by aurelien-reeves-scalingo** [comment]
Refs. https://github.com/Scalingo/documentation/pull/1742

**Comment by aurelien-reeves-scalingo** [comment]
CLI examples have been fixed as part of https://github.com/Scalingo/cli/pull/791
Documentation has been updated in https://github.com/Scalingo/documentation/pull/1742

 @QuentinEscudierScalingo @curzolapierre: do you think of anything else to check or to do?

**Comment by Soulou** [comment]
Closing as duplicata of #787
