### ISSUE TITLE
Autocomplete git remotes

### ISSUE THREAD

**Issue by yannski** [Scalingo/cli#82]
When having several remote on scalingo (for example, -staging and -production), it could be very handy for the CLI to autocomplete the name and complete on tab the name of the remotes :)

**Comment by Soulou** [comment]
I'll give a bit more explanation here, quite often people have the same application in different environments, example:

* myapplication-staging
* myapplication-production

In this case they have different GIT remotes:

```
scalingo	git@scalingo.com:scalingo-api-production.git
staging	git@scalingo.com:scalingo-api-staging.git
```

So what would be great is that when users are typing

```
scalingo -a scalingo-api-<TAB><TAB>
```

It gives them in priority the different remotes.

**Comment by Zyko0** [comment]
It is not possible at the moment, bash automatically sorts displayed results in alphabetical order, and there is no way to actually display them using our own sort logic.
This option is available on zsh, but implementing this would make scalingo's autocompletion, zsh-only compatible.

**Comment by Soulou** [comment]
The issue itself has been resolved, there is just the "priority part" which can be externalized in another issue.

https://github.com/Scalingo/cli/issues/134
