### ISSUE TITLE
CLI should be able to request API to send a signal to a container

### ISSUE THREAD

**Issue by QuentinEscudierScalingo** [Scalingo/cli#832]
Related to https://github.com/Scalingo/project-items/issues/3
Depends on https://github.com/Scalingo/api/issues/2095

CLI should request API via `POST /apps/:app_id/containers/:container_name/kill`

```
scalingo --app my-app send-signal --signal SIGUSR1 web-1
-----> Sending signal SIGUSR1 to "web-1" container.
```

**Comment by Soulou** [comment]
@QuentinEscudierScalingo don't forget to quote https://github.com/Scalingo/project-items/issues/3 in your issues to make the link
