### ISSUE TITLE
SSH agent based detection not working on windows powershell

### ISSUE THREAD

**Issue by SCedricThomas** [Scalingo/cli#902]
The SSH key is not detected under powershell even if the key add to the ssh-agent:
```
$ ssh -T ssh -T git@ssh.osc-fr1.scalingo.com
You've successfully authenticated on Scalingo, but there is no shell access
$ scalingo login
       Trying login with SSH…
 !     SSH connection failed.
       Trying login with user/password:

       Username or email: 
$ scalingo -a APP_NAME db-tunnel DB_URL
 fail to connect to SSH server: open C:\Users\USERNAME\.ssh\id_rsa: The system cannot find the file specified.
```

**Comment by guillaume-sc** [comment]
As [documented](https://doc.scalingo.com/platform/cli/start#windows), Scalingo recommends MS Windows user rely on [`git-bash`](https://git-for-windows.github.io/). We do not intend Scalingo CLI to be compatible with all available shells under MS Windows.
