### ISSUE TITLE
1.0.0-alpha4: Can't login from Windows

### ISSUE THREAD

**Issue by mweirauch** [Scalingo/cli#92]
$ scalingo.exe login
You need to be authenticated to use Scalingo client.
No account ? → https://my.scalingo.com/users/signup
Username or email: ****
Password: <DISPLAYED-IN-PLAIN-TEXT!!!>
Fail to login (1/3): json: cannot unmarshal object into Go value of type string
Username or email:

scalingo_1.0.0-alpha4_windows_amd64.zip is being used.

**Comment by Soulou** [comment]
Hi @mweirauch thank you for reporting the issue.

It has been fixed on master. I will release a new version of the tool tomorrow and everything will be fine.

If you can't wait, you can build master with the following command line

`go get github.com/Scalingo/cli/scalingo` (but you need a working go environment)

**Comment by Soulou** [comment]
(I know about the password in plain text for Windows, I'm looking for a fix ;-) )

**Comment by mweirauch** [comment]
Ah, thanks for the quick reply. Looking forward to it. Using Windows at home is a PITA :)

**Comment by Soulou** [comment]
Actually I'm currently deploying a fix on the API side to handle the error, I keep you in touch

**Comment by Soulou** [comment]
@mweirauch Ok, the fixed is in produciton, it should work right now, I close the issue, reopen if there is a problem.

**Comment by mweirauch** [comment]
Thanks for the quick fix! Working now!

**Comment by Soulou** [comment]
New version has been released https://github.com/Scalingo/cli/releases/tag/1.0.0-beta1
