### ISSUE TITLE
Too late response or no response from the cli!

### ISSUE THREAD

**Issue by ChetSocio** [Scalingo/cli#933]
I have downloaded scalingo cli latest version, logged in to it. And set up its cli properly. The problem is that most of the options that you stated in the documentation didnot worked on my end. I am using windows 10 pro.  And only some of the commands work for me like `scalingo keys`  , `scalingo self `,` scalingo whoami`

No other commands work on the terminal.Terminal doesnot show any response .I waited for 15 minutes after trying` scalingo create my-app` but sadly it didnot happen plus I didnot get any error messages. Please tell me how can I solve this.

**Comment by ipfaze** [comment]
Problem was solved through the support.
It was related to the current Windows issue with our CLI (#809)
