### ISSUE TITLE
redis-cli does not work through "run" command

### ISSUE THREAD

**Issue by yannski** [Scalingo/cli#95]
I can launch redis-cli but I cannot write any command in redis-cli prompt.

**Comment by Soulou** [comment]
Reason is: redis-cli expects `\r\n` as newline, when you're typing enter, it's only sending '\n' which is not part of the redis `RESP` protocol http://redis.io/topics/protocol

**Comment by Soulou** [comment]
Fixed with #111

Please use

```
scalingo redis-console
```
